### ISSUE TITLE
the uri shows 'UNKNOWN' when response is 200

### ISSUE THREAD

**Issue by esteban-coder** [MasterEvarior/spring-cloud-gateway-monitoring#1]
Great repository!
A question: the uri shows 'UNKNOWN' when response is 200, but can not see which of all the endpoints exposed is being consumed.

![image](https://github.com/MasterEvarior/spring-cloud-gateway-monitoring/assets/55806698/782d6916-3a3f-469d-bf3f-895df7994d43)

**Comment by MasterEvarior** [comment]
Hi and thanks :smiley: 

I am not entirely sure what the question is. If your question is which endpoint is consumed, it would be `/200`. If you want to read this from the data sent to Grafana, there should be a tag 'path' which can give you the information. You would still need to visualize it somehow but the data should be there.

**Comment by esteban-coder** [comment]
Hello @MasterEvarior, what if I create other endpoins or routes (for instance: /ok, /success, /created, /done, etc) that responds 200?
In the graphic, how could I differentiate them? Calls to all of these endpoints would be "grouped by" 'UNKNOWN' and what I would expect is to get the metrics for '/200/, other metrics for '/ok', metrics for '/success', and so on.

**Comment by MasterEvarior** [comment]
You'd have to make a new graph, that splits the requests by path, instead of by status code. If you don't know much about Grafana/Prometheus/PromQl, I'd start with [this guide here](https://grafana.com/tutorials/grafana-fundamentals/?pg=tutorials&plcmt=results).

**Comment by esteban-coder** [comment]
Requests by path, the only path is "UNKNOWN" (instead of '/200', '/ok', '/success', '/created'), and requests by status code is as your graph shows, but I would expected in that graph to be GET[200] /200 instead of GET[200] UNKNOWN.

**Comment by MasterEvarior** [comment]
Again, if you want to see the requests by path, you will have to make a new graph with an appropriate query. A query like `sum(gateway_requests_total) by (path)` will net you graph like this:
![image](https://github.com/MasterEvarior/spring-cloud-gateway-monitoring/assets/36074738/3d4a9433-d6c1-4917-919f-3b8b454bb614)

What may be a bit confusing is that the route, which returns 200 OK, is literally called `/200`. This is not the status code, it is just the name of the endpoint.
